version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-sample
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass yourpassword  # Redis 비밀번호 설정

volumes:
  redis-data: 